import { useState } from "react";
export default function Myuserid()
{
    const[myid,setId]=useState([]);
    const[myloader,setLoader]=useState(false);
    function fetchdatafromapi()
    {
        setLoader(true)
        fetch("https://randomuser.me/api/?results=5")
        .then((res)=>{
            return(res.json())
        })
        .then((response)=>{
            //console.log(response.results);
            //it will be an array
            setId(response.results);
            setLoader(false);
        })
    }
    function getData()
    {
        return(
            <>
            <button onClick={()=>{fetchdatafromapi()}}>Click me to get autogenerated emails</button>
            
            <div>
                {myid.map((item,index)=>{
                    return <h2 key={index}>{item.email}</h2>
                })}
            </div>
            </>
            
        )
    }
    return myloader?<><h2>Loading</h2></>:getData()
    
}























// import { useState } from "react";

// export default function Myusersid()
// {
//     const[userids,setuserId]=useState([]);
//     function fetchIdFromAPI()
//     {
//         fetch("https://randomuser.me/api/?results=5")
//         .then((res)=>{
//             return(res.json())
//         })
//         .then((response=>{
//             //console.log(response.results);
//             setuserId(response.results);
//             console.log("Done")
//         }))
//         .catch((err)=>{
//             console.log('Error while fetching users ', err);
//         })
//     }
//     return(
//         <>
//         <button onClick={()=>fetchIdFromAPI()}>Click me to get 5 random ids</button>
//         {userids.map((item,index)=>{
//             return <h2 key={index}>{item.email}</h2>
//         })}
        
//         </>
//     );
// }